//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoservicesRul.Entityes
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }

        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategory { get; set; }
        public string ProductImage { get; set; }
        public int IdManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string Unit { get; set; }
        public byte MaxDiscountAmount { get; set; }
        public int Supplier { get; set; }
        public string ProductStatus { get; set; }
        public Nullable<int> CountInPack { get; set; }
        public Nullable<int> MinCount { get; set; }
        public Nullable<bool> Deleted { get; set; }

        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Supplier Supplier1 { get; set; }

        public string Background
        {
            get
            {
                if (this.ProductDiscountAmount > 15)
                    return "#7fff00";
                return "#fff";
            }
        }
        public string Cost
        {
            get
            {
                var costWithDiscount = Convert.ToDouble(this.ProductCost);
                return costWithDiscount.ToString() + " рублей";

            }
        }
        public string CostWithDiscount
        {
            get
            {
                if (this.ProductDiscountAmount > 0)
                {
                    var costWithDiscount = Convert.ToDouble(this.ProductCost) - Convert.ToDouble(this.ProductCost) * Convert.ToDouble(this.ProductDiscountAmount / 100.00);
                    return costWithDiscount.ToString() + " рублей";
                }
                return "";
            }
        }
        public string CostWithDiscountStrikethrough
        {
            get
            {
                if (this.ProductDiscountAmount > 0)
                {
                    return "Strikethrough";
                }
                return "";
            }
        }
        public string ImgPath
        {
            get
            {
                var path = "pack://application:,,,/Resources/" + this.ProductImage;
                return path;
            }
        }
    }
}
